services:
    netdash-dev:
        build:
            context: .
            dockerfile: docker/dev-runtime/Dockerfile
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/app'
        depends_on:
            - buggregator
    buggregator:
        image: ghcr.io/buggregator/server:latest
        ports:
            - 8000:8000
            - 1025:1025
            - 9912:9912
            - 9913:9913
