services:
    # franken:
    #     build:
    #         context: ./
    #         dockerfile: ./docker/prod2/Dockerfile
    #     ports:
    #         - "8888:80"
    #     environment:
    #         CADDY_GLOBAL_OPTIONS: auto_https off
    #         SERVER_NAME: "http://localhost"
    #     volumes:
    #         - ./.env:/app/.env

    octane:
        build:
            context: ./
            dockerfile: ./docker/prod/Dockerfile
        ports:
            - "8888:8000"
        volumes:
            - ./.env:/app/.env