name: Laravel

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
      - app/**
      - bootstrap/**
      - config/**
      - database/**
      - routes/**
      - tests/**

jobs:
  laravel-cs-and-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@d30ad8b1843ace22e6698ab99bbafaa747b6bd0d
      with:
        php-version: '8.3'
    - uses: actions/checkout@v3
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Run Pint
      run: vendor/bin/pint --test
    - name: Run PHPStan
      run: vendor/bin/phpstan
    - name: Run Pest
      run: vendor/bin/pest